network:
  threads: 4
  rcvbuf: 131072
  connectTimeout: 5000
  idleTimeout: 5000
connections:
  - url: rtsp://localhost:8554/picture
    n: 2000
# you can also add custom path here
# - url: rtsp://localhost:8554/file?file=<path-to-video-file>.mkv
#  n: 2000